<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.CN.NET.Sdk/15.0.0">

    <PropertyGroup>
        <Version>1.3.6.0</Version>
        <Name>FriendCompass</Name>
        <Authors>Lotusloyi</Authors>
        <Author>Lotusloyi</Author>
        <Description>FriendCompass 好友罗盘：查询好友地区、服务器、职业；同图显示方向、距离、头顶标记与地图标记；支持分流切换、区域玩家名单和上下线提醒。</Description>
        <Punchline>好友罗盘：箭头指向同图好友</Punchline>
        <RepositoryUrl>https://github.com/Lotusloyi/FFXIV-Dalamud-Plugins</RepositoryUrl>
        <RepoUrl>https://github.com/Lotusloyi/FFXIV-Dalamud-Plugins</RepoUrl>
        <PackageProjectUrl>https://github.com/Lotusloyi/FFXIV-Dalamud-Plugins</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Tags>friend;compass;tracker;map;arrow;ff14;dalamud;plugin</Tags>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

</Project>
